'use strict';

const PDFDocument = require('pdfkit');
const { formatCurrency } = require('../nlp/languages');

/**
 * Generate a GST-compliant invoice PDF as a Buffer.
 *
 * @param {object} invoiceData
 * @param {string} invoiceData.invoiceNumber
 * @param {string} invoiceData.date
 * @param {string} invoiceData.customerName
 * @param {string|null} invoiceData.gstin
 * @param {Array<{name: string, quantity: number, price: number}>} invoiceData.items
 * @param {number} invoiceData.subtotal
 * @param {number} invoiceData.gstRate
 * @param {number} invoiceData.gstAmount
 * @param {number} invoiceData.total
 * @param {string} invoiceData.language
 * @returns {Promise<Buffer>}
 */
function generateInvoicePdf(invoiceData) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const buffers = [];

    doc.on('data', (chunk) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const {
      invoiceNumber,
      date,
      customerName,
      gstin,
      items,
      subtotal,
      gstRate,
      gstAmount,
      total,
    } = invoiceData;

    // ── Header ────────────────────────────────────────────────────────
    doc
      .fontSize(22)
      .fillColor('#1a1a2e')
      .text('TAX INVOICE', { align: 'center' });

    doc
      .fontSize(10)
      .fillColor('#666')
      .text('VyapaarAI — AI Business OS for Indian MSMEs', { align: 'center' });

    doc.moveDown(0.5);
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor('#e0e0e0')
      .stroke();
    doc.moveDown(0.5);

    // ── Invoice Meta ──────────────────────────────────────────────────
    const leftX = 50;
    const rightX = 350;

    doc.fontSize(10).fillColor('#333');
    doc.text(`Invoice No: `, leftX, doc.y, { continued: true }).font('Helvetica-Bold').text(invoiceNumber);
    doc.font('Helvetica').text(`Date: `, leftX, doc.y, { continued: true }).font('Helvetica-Bold').text(date);

    if (gstin) {
      doc.font('Helvetica').text(`Customer GSTIN: `, leftX, doc.y, { continued: true }).font('Helvetica-Bold').text(gstin);
    }

    doc.moveDown(0.5);

    // ── Bill To ───────────────────────────────────────────────────────
    doc
      .font('Helvetica-Bold')
      .fontSize(11)
      .fillColor('#1a1a2e')
      .text('Bill To:', leftX);

    doc
      .font('Helvetica')
      .fontSize(10)
      .fillColor('#333')
      .text(customerName, leftX);

    doc.moveDown(1);

    // ── Items Table Header ────────────────────────────────────────────
    const tableTop = doc.y;
    const colItem = 50;
    const colQty = 310;
    const colPrice = 380;
    const colTotal = 460;

    doc
      .rect(50, tableTop, 495, 20)
      .fillColor('#1a1a2e')
      .fill();

    doc
      .fillColor('#ffffff')
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('Item / Description', colItem + 5, tableTop + 5)
      .text('Qty', colQty, tableTop + 5)
      .text('Price', colPrice, tableTop + 5)
      .text('Total', colTotal, tableTop + 5);

    // ── Items Rows ────────────────────────────────────────────────────
    let rowY = tableTop + 25;
    doc.font('Helvetica').fontSize(10).fillColor('#333');

    items.forEach((item, idx) => {
      const rowBg = idx % 2 === 0 ? '#f9f9f9' : '#ffffff';
      doc.rect(50, rowY - 3, 495, 20).fillColor(rowBg).fill();

      const itemPrice = item.price != null ? item.price : 0;
      const itemQty = item.quantity != null ? item.quantity : 1;
      const itemTotal = itemPrice * itemQty;
      doc
        .fillColor('#333')
        .text(item.name || 'Item', colItem + 5, rowY)
        .text(String(itemQty), colQty, rowY)
        .text(formatCurrency(itemPrice), colPrice, rowY)
        .text(formatCurrency(itemTotal), colTotal, rowY);

      rowY += 22;
    });

    doc.moveDown(0.5);

    // ── Totals ────────────────────────────────────────────────────────
    const totalsY = rowY + 10;
    const labelX = 380;
    const valueX = 460;

    doc.font('Helvetica').fontSize(10).fillColor('#333');
    doc.text('Subtotal:', labelX, totalsY).text(formatCurrency(subtotal), valueX, totalsY);
    doc.text(`GST (${gstRate}%):`, labelX, totalsY + 18).text(formatCurrency(gstAmount), valueX, totalsY + 18);

    doc
      .moveTo(labelX, totalsY + 36)
      .lineTo(545, totalsY + 36)
      .strokeColor('#aaa')
      .stroke();

    doc
      .font('Helvetica-Bold')
      .fontSize(12)
      .fillColor('#1a1a2e')
      .text('TOTAL:', labelX, totalsY + 42)
      .text(formatCurrency(total), valueX, totalsY + 42);

    // ── Footer ────────────────────────────────────────────────────────
    doc
      .fontSize(9)
      .fillColor('#999')
      .text(
        'Generated by VyapaarAI · AI Business OS for Indian MSMEs · vyapaarai.in',
        50,
        doc.page.height - 60,
        { align: 'center', width: 495 },
      );

    doc.end();
  });
}

module.exports = { generateInvoicePdf };
